exclude: >
  (?x)^(
    gen/
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.4.0
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/nametake/pre-commit-buf
    rev: v2.0.0
    hooks:
      - id: buf-lint
      - id: buf-breaking
        args: [ .git#branch=main ]
